//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-02-17
//     Last Modified: 2025-02-17
//     Description: 
//       Defines a specification for applying advanced filtering options to the 
//       Subject entity, supporting different views and keyword-based searches.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Application.Features.Subjects.Specifications;
#nullable disable warnings
/// <summary>
/// Specification class for advanced filtering of Subjects.
/// </summary>
public class SubjectAdvancedSpecification : Specification<Subject>
{
    public SubjectAdvancedSpecification(SubjectAdvancedFilter filter)
    {
        DateTime today = DateTime.UtcNow;
        var todayrange = today.GetDateRange(SubjectListView.TODAY.ToString(), filter.LocalTimezoneOffset);
        var last30daysrange = today.GetDateRange(SubjectListView.LAST_30_DAYS.ToString(),filter.LocalTimezoneOffset);

        Query.Where(q => q.Name != null)
             .Where(filter.Keyword,!string.IsNullOrEmpty(filter.Keyword))
             .Where(q => q.CreatedBy == filter.CurrentUser.UserId, filter.ListView == SubjectListView.My && filter.CurrentUser is not null)
             .Where(x => x.Created >= todayrange.Start && x.Created < todayrange.End.AddDays(1), filter.ListView == SubjectListView.TODAY)
             .Where(x => x.Created >= last30daysrange.Start, filter.ListView == SubjectListView.LAST_30_DAYS);
       
    }
}
