//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-02-17
//     Last Modified: 2025-02-17
//     Description: 
//       Defines a specification for filtering a Subject entity by its ID.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Application.Features.Subjects.Specifications;
#nullable disable warnings
/// <summary>
/// Specification class for filtering Subjects by their ID.
/// </summary>
public class SubjectByIdSpecification : Specification<Subject>
{
    public SubjectByIdSpecification(int id)
    {
       Query.Where(q => q.Id == id);
    }
}