//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-02-17
//     Last Modified: 2025-02-17
//     Description: 
//       Configures the properties and behaviors for the `Subject` entity in the 
//       database. Specifies property constraints such as maximum length and required fields.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CleanArchitecture.Blazor.Infrastructure.Persistence.Configurations;

#nullable disable
public class SubjectConfiguration : IEntityTypeConfiguration<Subject>
{
    public void Configure(EntityTypeBuilder<Subject> builder)
    {
            builder.Property(x => x.Code).HasMaxLength(50); 
            builder.HasIndex(x => x.Name); 
            builder.Property(x => x.Name).HasMaxLength(255).IsRequired(); 
            builder.Property(x => x.Description).HasMaxLength(255);
            builder.Ignore(e => e.DomainEvents);
    }
}


