//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-02-17
//     Last Modified: 2025-02-17
//     Description: 
//       Defines mapping methods between `Subject` entities and related DTOs/commands 
//       within the CleanArchitecture.Blazor application. This mapper facilitates 
//       conversions to support different operations, such as creating, updating, 
//       and projecting subject data.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Application.Features.Subjects.Commands.AddEdit;
using CleanArchitecture.Blazor.Application.Features.Subjects.Commands.Create;
using CleanArchitecture.Blazor.Application.Features.Subjects.Commands.Update;
using CleanArchitecture.Blazor.Application.Features.Subjects.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.Subjects.Mappers;

#pragma warning disable RMG020
#pragma warning disable RMG012
[Mapper]
public static partial class SubjectMapper
{
    public static partial SubjectDto ToDto(Subject source);
    public static partial Subject FromDto(SubjectDto dto);
    public static partial Subject FromEditCommand(AddEditSubjectCommand command);
    public static partial Subject FromCreateCommand(CreateSubjectCommand command);
    public static partial UpdateSubjectCommand ToUpdateCommand(SubjectDto dto);
    public static partial AddEditSubjectCommand CloneFromDto(SubjectDto dto);
    public static partial void ApplyChangesFrom(UpdateSubjectCommand source, Subject target);
    public static partial void ApplyChangesFrom(AddEditSubjectCommand source, Subject target);
    public static partial IQueryable<SubjectDto> ProjectTo(this IQueryable<Subject> q);
}

