//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-02-17
//     Last Modified: 2025-02-17
//     Description: 
//       Defines permission constants for subject-related operations, such as 
//       viewing, creating, editing, deleting, and more. These permissions are 
//       used to manage access control within the application.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CleanArchitecture.Blazor.Infrastructure.PermissionSet;

public static partial class Permissions
{
    [DisplayName("Subject Permissions")]
    [Description("Set permissions for subject operations.")]
    public static class Subjects
    {
        [Description("Allows viewing subject details.")]
        public const string View = "Permissions.Subjects.View";
        [Description("Allows creating subject details.")]
        public const string Create = "Permissions.Subjects.Create";
        [Description("Allows editing subject details.")]
        public const string Edit = "Permissions.Subjects.Edit";
        [Description("Allows deleting subject details.")]
        public const string Delete = "Permissions.Subjects.Delete";
        [Description("Allows printing subject details.")]
        public const string Print = "Permissions.Subjects.Print";
        [Description("Allows searching subject details.")]
        public const string Search = "Permissions.Subjects.Search";
        [Description("Allows exporting subject details.")]
        public const string Export = "Permissions.Subjects.Export";
        [Description("Allows importing subject details.")]
        public const string Import = "Permissions.Subjects.Import";
    }
}

