//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-02-17
//     Last Modified: 2025-02-17
//     Description: 
//       This file defines the command and its handler for creating a new Subject entity
//       within the CleanArchitecture.Blazor application. The command uses caching
//       invalidation to ensure data consistency and raises domain events to maintain 
//       the integrity of the entity lifecycle. It leverages Clean Architecture principles 
//       for separation of concerns and encapsulation.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/subject
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// This command can be used to create a new subject entity in the system. It includes
// the required fields for the subject and automatically raises necessary domain
// events for integration with other bounded contexts in the application.

using CleanArchitecture.Blazor.Application.Features.Subjects.Caching;
using CleanArchitecture.Blazor.Application.Features.Subjects.Mappers;

namespace CleanArchitecture.Blazor.Application.Features.Subjects.Commands.Create;

public class CreateSubjectCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
          [Description("Code")]
    public string? Code {get;set;} 
    [Description("Name")]
    public string Name {get;set;} 
    [Description("Description")]
    public string? Description {get;set;} 

      public string CacheKey => SubjectCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => SubjectCacheKey.Tags;
}
    
    public class CreateSubjectCommandHandler : IRequestHandler<CreateSubjectCommand, Result<int>>
    {
        private readonly IApplicationDbContext _context;
        public CreateSubjectCommandHandler(
            IApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<Result<int>> Handle(CreateSubjectCommand request, CancellationToken cancellationToken)
        {
           var item = SubjectMapper.FromCreateCommand(request);
           // raise a create domain event
	       item.AddDomainEvent(new SubjectCreatedEvent(item));
           _context.Subjects.Add(item);
           await _context.SaveChangesAsync(cancellationToken);
           return  await Result<int>.SuccessAsync(item.Id);
        }
    }

