//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-02-17
//     Last Modified: 2025-02-17
//     Description: 
//       Defines a query to export subject data to an Excel file. This query 
//       applies advanced filtering options and generates an Excel file with 
//       the specified subject details.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Application.Features.Subjects.DTOs;
using CleanArchitecture.Blazor.Application.Features.Subjects.Mappers;
using CleanArchitecture.Blazor.Application.Features.Subjects.Caching;
using CleanArchitecture.Blazor.Application.Features.Subjects.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Subjects.Queries.Export;

public class ExportSubjectsQuery : SubjectAdvancedFilter, ICacheableRequest<Result<byte[]>>
{
      public SubjectAdvancedSpecification Specification => new SubjectAdvancedSpecification(this);
      public IEnumerable<string>? Tags => SubjectCacheKey.Tags;
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}-{LocalTimezoneOffset.TotalHours}, Search:{Keyword}, {OrderBy}, {SortDirection}";
    }
    public string CacheKey => SubjectCacheKey.GetExportCacheKey($"{this}");
}
    
public class ExportSubjectsQueryHandler :
         IRequestHandler<ExportSubjectsQuery, Result<byte[]>>
{
        private readonly IApplicationDbContext _context;
        private readonly IExcelService _excelService;
        private readonly IStringLocalizer<ExportSubjectsQueryHandler> _localizer;
        private readonly SubjectDto _dto = new();
        public ExportSubjectsQueryHandler(
            IApplicationDbContext context,
            IExcelService excelService,
            IStringLocalizer<ExportSubjectsQueryHandler> localizer
            )
        {
            _context = context;
            _excelService = excelService;
            _localizer = localizer;
        }
        #nullable disable warnings
        public async Task<Result<byte[]>> Handle(ExportSubjectsQuery request, CancellationToken cancellationToken)
        {
            var data = await _context.Subjects.ApplySpecification(request.Specification)
                       .OrderBy($"{request.OrderBy} {request.SortDirection}")
                       .ProjectTo()
                       .AsNoTracking()
                       .ToListAsync(cancellationToken);
            var result = await _excelService.ExportAsync(data,
                new Dictionary<string, Func<SubjectDto, object?>>()
                {
                    // TODO: Define the fields that should be exported, for example:
                    {_localizer[_dto.GetMemberDescription(x=>x.Code)],item => item.Code}, 
{_localizer[_dto.GetMemberDescription(x=>x.Name)],item => item.Name}, 
{_localizer[_dto.GetMemberDescription(x=>x.Description)],item => item.Description}, 

                }
                , _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
}
