//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-02-17
//     Last Modified: 2025-02-17
//     Description: 
//       This file defines the Data Transfer Object (DTO) for the Subject entity 
//       used within the CleanArchitecture.Blazor application. The SubjectDto is 
//       responsible for transferring data between layers while maintaining the 
//       structure and format required by application features like commands, queries, 
//       and views.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/subject
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// The `SubjectDto` class is used to represent subject data throughout the CleanArchitecture.Blazor
// application, providing a well-defined contract for passing subject information between different 
// layers and services. Each property includes a description for better understandability during 
// serialization and documentation generation.

namespace CleanArchitecture.Blazor.Application.Features.Subjects.DTOs;

[Description("Subjects")]
public class SubjectDto
{
    [Description("Id")]
    public int Id { get; set; }
        [Description("Code")]
    public string? Code {get;set;} 
    [Description("Name")]
    public string Name {get;set;} 
    [Description("Description")]
    public string? Description {get;set;} 


}

