//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-02-17
//     Last Modified: 2025-02-17
//     Description: 
//       This file defines the command for adding or editing a subject entity,
//       including validation and mapping operations. It handles domain events
//       and cache invalidation for updated or newly created subject.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/subject
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// This command can be used to add a new subject or edit an existing one.
// It handles caching logic and domain event raising automatically.


using CleanArchitecture.Blazor.Application.Features.Subjects.Caching;
using CleanArchitecture.Blazor.Application.Features.Subjects.Mappers;

namespace CleanArchitecture.Blazor.Application.Features.Subjects.Commands.AddEdit;

public class AddEditSubjectCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
          [Description("Code")]
    public string? Code {get;set;} 
    [Description("Name")]
    public string Name {get;set;} 
    [Description("Description")]
    public string? Description {get;set;} 


      public string CacheKey => SubjectCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => SubjectCacheKey.Tags;
}

public class AddEditSubjectCommandHandler : IRequestHandler<AddEditSubjectCommand, Result<int>>
{
    private readonly IApplicationDbContext _context;
    public AddEditSubjectCommandHandler(
        IApplicationDbContext context)
    {
        _context = context;
    }
    public async Task<Result<int>> Handle(AddEditSubjectCommand request, CancellationToken cancellationToken)
    {
        if (request.Id > 0)
        {
            var item = await _context.Subjects.FindAsync(request.Id, cancellationToken);
            if (item == null)
            {
                return await Result<int>.FailureAsync($"Subject with id: [{request.Id}] not found.");
            }
            SubjectMapper.ApplyChangesFrom(request,item);
			// raise a update domain event
			item.AddDomainEvent(new SubjectUpdatedEvent(item));
            await _context.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
        else
        {
            var item = SubjectMapper.FromEditCommand(request);
            // raise a create domain event
			item.AddDomainEvent(new SubjectCreatedEvent(item));
            _context.Subjects.Add(item);
            await _context.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
       
    }
}

