//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-02-17
//     Last Modified: 2025-02-17
//     Description: 
//       Defines a query to retrieve a subject by its ID. The result is cached 
//       to optimize performance for repeated retrievals of the same subject.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Application.Features.Subjects.DTOs;
using CleanArchitecture.Blazor.Application.Features.Subjects.Caching;
using CleanArchitecture.Blazor.Application.Features.Subjects.Mappers;
using CleanArchitecture.Blazor.Application.Features.Subjects.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Subjects.Queries.GetById;

public class GetSubjectByIdQuery : ICacheableRequest<Result<SubjectDto>>
{
   public required int Id { get; set; }
   public string CacheKey => SubjectCacheKey.GetByIdCacheKey($"{Id}");
   public IEnumerable<string>? Tags => SubjectCacheKey.Tags;
}

public class GetSubjectByIdQueryHandler :
     IRequestHandler<GetSubjectByIdQuery, Result<SubjectDto>>
{
    private readonly IApplicationDbContext _context;

    public GetSubjectByIdQueryHandler(
        IApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<Result<SubjectDto>> Handle(GetSubjectByIdQuery request, CancellationToken cancellationToken)
    {
        var data = await _context.Subjects.ApplySpecification(new SubjectByIdSpecification(request.Id))
                                                .ProjectTo()
                                                .FirstAsync(cancellationToken);
        return await Result<SubjectDto>.SuccessAsync(data);
    }
}
